//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 01:37:51 PM CET 
//


package com.KnowledgePioneer.backEndTask.entity;

import javax.xml.namespace.QName;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.beansg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QuestelPatentDocumentDescriptionPBr_QNAME = new QName("", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.beansg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuestelPatentDocument }
     * 
     */
    public QuestelPatentDocument createQuestelPatentDocument() {
        return new QuestelPatentDocument();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.Claims }
     * 
     */
    public QuestelPatentDocument.Claims createQuestelPatentDocumentClaims() {
        return new QuestelPatentDocument.Claims();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.Description }
     * 
     */
    public QuestelPatentDocument.Description createQuestelPatentDocumentDescription() {
        return new QuestelPatentDocument.Description();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.Abstract }
     * 
     */
    public QuestelPatentDocument.Abstract createQuestelPatentDocumentAbstract() {
        return new QuestelPatentDocument.Abstract();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData }
     * 
     */
    public QuestelPatentDocument.BibliographicData createQuestelPatentDocumentBibliographicData() {
        return new QuestelPatentDocument.BibliographicData();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Examiners }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Examiners createQuestelPatentDocumentBibliographicDataExaminers() {
        return new QuestelPatentDocument.BibliographicData.Examiners();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties createQuestelPatentDocumentBibliographicDataParties() {
        return new QuestelPatentDocument.BibliographicData.Parties();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Agents }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Agents createQuestelPatentDocumentBibliographicDataPartiesAgents() {
        return new QuestelPatentDocument.BibliographicData.Parties.Agents();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Agents.Agent }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Agents.Agent createQuestelPatentDocumentBibliographicDataPartiesAgentsAgent() {
        return new QuestelPatentDocument.BibliographicData.Parties.Agents.Agent();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Inventors }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Inventors createQuestelPatentDocumentBibliographicDataPartiesInventors() {
        return new QuestelPatentDocument.BibliographicData.Parties.Inventors();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor createQuestelPatentDocumentBibliographicDataPartiesInventorsInventor() {
        return new QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Addressbook }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Addressbook createQuestelPatentDocumentBibliographicDataPartiesInventorsInventorAddressbook() {
        return new QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Addressbook();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Applicants }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Applicants createQuestelPatentDocumentBibliographicDataPartiesApplicants() {
        return new QuestelPatentDocument.BibliographicData.Parties.Applicants();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant createQuestelPatentDocumentBibliographicDataPartiesApplicantsApplicant() {
        return new QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Addressbook }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Addressbook createQuestelPatentDocumentBibliographicDataPartiesApplicantsApplicantAddressbook() {
        return new QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Addressbook();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.RelatedDocuments }
     * 
     */
    public QuestelPatentDocument.BibliographicData.RelatedDocuments createQuestelPatentDocumentBibliographicDataRelatedDocuments() {
        return new QuestelPatentDocument.BibliographicData.RelatedDocuments();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.RelatedDocuments.Division }
     * 
     */
    public QuestelPatentDocument.BibliographicData.RelatedDocuments.Division createQuestelPatentDocumentBibliographicDataRelatedDocumentsDivision() {
        return new QuestelPatentDocument.BibliographicData.RelatedDocuments.Division();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation }
     * 
     */
    public QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation createQuestelPatentDocumentBibliographicDataRelatedDocumentsDivisionRelation() {
        return new QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation.ParentDoc }
     * 
     */
    public QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation.ParentDoc createQuestelPatentDocumentBibliographicDataRelatedDocumentsDivisionRelationParentDoc() {
        return new QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation.ParentDoc();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ReferencesCited }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ReferencesCited createQuestelPatentDocumentBibliographicDataReferencesCited() {
        return new QuestelPatentDocument.BibliographicData.ReferencesCited();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ReferencesCited.Citation }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ReferencesCited.Citation createQuestelPatentDocumentBibliographicDataReferencesCitedCitation() {
        return new QuestelPatentDocument.BibliographicData.ReferencesCited.Citation();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Patcit }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Patcit createQuestelPatentDocumentBibliographicDataReferencesCitedCitationPatcit() {
        return new QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Patcit();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Figures }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Figures createQuestelPatentDocumentBibliographicDataFigures() {
        return new QuestelPatentDocument.BibliographicData.Figures();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PatentClassifications }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PatentClassifications createQuestelPatentDocumentBibliographicDataPatentClassifications() {
        return new QuestelPatentDocument.BibliographicData.PatentClassifications();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification createQuestelPatentDocumentBibliographicDataPatentClassificationsPatentClassification() {
        return new QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsEcla }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsEcla createQuestelPatentDocumentBibliographicDataClassificationsEcla() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsEcla();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationNational }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationNational createQuestelPatentDocumentBibliographicDataClassificationNational() {
        return new QuestelPatentDocument.BibliographicData.ClassificationNational();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsIpcr }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsIpcr createQuestelPatentDocumentBibliographicDataClassificationsIpcr() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsIpcr();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr createQuestelPatentDocumentBibliographicDataClassificationsIpcrClassificationIpcr() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.DatesOfPublicAvailability }
     * 
     */
    public QuestelPatentDocument.BibliographicData.DatesOfPublicAvailability createQuestelPatentDocumentBibliographicDataDatesOfPublicAvailability() {
        return new QuestelPatentDocument.BibliographicData.DatesOfPublicAvailability();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PriorityClaims }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PriorityClaims createQuestelPatentDocumentBibliographicDataPriorityClaims() {
        return new QuestelPatentDocument.BibliographicData.PriorityClaims();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ApplicationReference }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ApplicationReference createQuestelPatentDocumentBibliographicDataApplicationReference() {
        return new QuestelPatentDocument.BibliographicData.ApplicationReference();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PublicationReference }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PublicationReference createQuestelPatentDocumentBibliographicDataPublicationReference() {
        return new QuestelPatentDocument.BibliographicData.PublicationReference();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.Claims.Claim }
     * 
     */
    public QuestelPatentDocument.Claims.Claim createQuestelPatentDocumentClaimsClaim() {
        return new QuestelPatentDocument.Claims.Claim();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.Description.P }
     * 
     */
    public QuestelPatentDocument.Description.P createQuestelPatentDocumentDescriptionP() {
        return new QuestelPatentDocument.Description.P();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.Abstract.P }
     * 
     */
    public QuestelPatentDocument.Abstract.P createQuestelPatentDocumentAbstractP() {
        return new QuestelPatentDocument.Abstract.P();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.InventionTitle }
     * 
     */
    public QuestelPatentDocument.BibliographicData.InventionTitle createQuestelPatentDocumentBibliographicDataInventionTitle() {
        return new QuestelPatentDocument.BibliographicData.InventionTitle();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.LgstData }
     * 
     */
    public QuestelPatentDocument.BibliographicData.LgstData createQuestelPatentDocumentBibliographicDataLgstData() {
        return new QuestelPatentDocument.BibliographicData.LgstData();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Examiners.PrimaryExaminer }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Examiners.PrimaryExaminer createQuestelPatentDocumentBibliographicDataExaminersPrimaryExaminer() {
        return new QuestelPatentDocument.BibliographicData.Examiners.PrimaryExaminer();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Agents.Agent.Addressbook }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Agents.Agent.Addressbook createQuestelPatentDocumentBibliographicDataPartiesAgentsAgentAddressbook() {
        return new QuestelPatentDocument.BibliographicData.Parties.Agents.Agent.Addressbook();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Nationality }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Nationality createQuestelPatentDocumentBibliographicDataPartiesInventorsInventorNationality() {
        return new QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Nationality();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Addressbook.Address }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Addressbook.Address createQuestelPatentDocumentBibliographicDataPartiesInventorsInventorAddressbookAddress() {
        return new QuestelPatentDocument.BibliographicData.Parties.Inventors.Inventor.Addressbook.Address();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Nationality }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Nationality createQuestelPatentDocumentBibliographicDataPartiesApplicantsApplicantNationality() {
        return new QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Nationality();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Addressbook.Address }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Addressbook.Address createQuestelPatentDocumentBibliographicDataPartiesApplicantsApplicantAddressbookAddress() {
        return new QuestelPatentDocument.BibliographicData.Parties.Applicants.Applicant.Addressbook.Address();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation.ParentDoc.DocumentId }
     * 
     */
    public QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation.ParentDoc.DocumentId createQuestelPatentDocumentBibliographicDataRelatedDocumentsDivisionRelationParentDocDocumentId() {
        return new QuestelPatentDocument.BibliographicData.RelatedDocuments.Division.Relation.ParentDoc.DocumentId();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Nplcit }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Nplcit createQuestelPatentDocumentBibliographicDataReferencesCitedCitationNplcit() {
        return new QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Nplcit();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Patcit.DocumentId }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Patcit.DocumentId createQuestelPatentDocumentBibliographicDataReferencesCitedCitationPatcitDocumentId() {
        return new QuestelPatentDocument.BibliographicData.ReferencesCited.Citation.Patcit.DocumentId();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.Figures.ImageKey }
     * 
     */
    public QuestelPatentDocument.BibliographicData.Figures.ImageKey createQuestelPatentDocumentBibliographicDataFiguresImageKey() {
        return new QuestelPatentDocument.BibliographicData.Figures.ImageKey();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification.ClassificationScheme }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification.ClassificationScheme createQuestelPatentDocumentBibliographicDataPatentClassificationsPatentClassificationClassificationScheme() {
        return new QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification.ClassificationScheme();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification.ActionDate }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification.ActionDate createQuestelPatentDocumentBibliographicDataPatentClassificationsPatentClassificationActionDate() {
        return new QuestelPatentDocument.BibliographicData.PatentClassifications.PatentClassification.ActionDate();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsEcla.ClassificationEcla }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsEcla.ClassificationEcla createQuestelPatentDocumentBibliographicDataClassificationsEclaClassificationEcla() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsEcla.ClassificationEcla();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationNational.MainClassification }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationNational.MainClassification createQuestelPatentDocumentBibliographicDataClassificationNationalMainClassification() {
        return new QuestelPatentDocument.BibliographicData.ClassificationNational.MainClassification();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationNational.FurtherClassification }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationNational.FurtherClassification createQuestelPatentDocumentBibliographicDataClassificationNationalFurtherClassification() {
        return new QuestelPatentDocument.BibliographicData.ClassificationNational.FurtherClassification();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.IpcVersionIndicator }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.IpcVersionIndicator createQuestelPatentDocumentBibliographicDataClassificationsIpcrClassificationIpcrIpcVersionIndicator() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.IpcVersionIndicator();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.GeneratingOffice }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.GeneratingOffice createQuestelPatentDocumentBibliographicDataClassificationsIpcrClassificationIpcrGeneratingOffice() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.GeneratingOffice();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.ActionDate }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.ActionDate createQuestelPatentDocumentBibliographicDataClassificationsIpcrClassificationIpcrActionDate() {
        return new QuestelPatentDocument.BibliographicData.ClassificationsIpcr.ClassificationIpcr.ActionDate();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.DatesOfPublicAvailability.PublicationOfGrantDate }
     * 
     */
    public QuestelPatentDocument.BibliographicData.DatesOfPublicAvailability.PublicationOfGrantDate createQuestelPatentDocumentBibliographicDataDatesOfPublicAvailabilityPublicationOfGrantDate() {
        return new QuestelPatentDocument.BibliographicData.DatesOfPublicAvailability.PublicationOfGrantDate();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PriorityClaims.PriorityClaim }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PriorityClaims.PriorityClaim createQuestelPatentDocumentBibliographicDataPriorityClaimsPriorityClaim() {
        return new QuestelPatentDocument.BibliographicData.PriorityClaims.PriorityClaim();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.ApplicationReference.DocumentId }
     * 
     */
    public QuestelPatentDocument.BibliographicData.ApplicationReference.DocumentId createQuestelPatentDocumentBibliographicDataApplicationReferenceDocumentId() {
        return new QuestelPatentDocument.BibliographicData.ApplicationReference.DocumentId();
    }

    /**
     * Create an instance of {@link QuestelPatentDocument.BibliographicData.PublicationReference.DocumentId }
     * 
     */
    public QuestelPatentDocument.BibliographicData.PublicationReference.DocumentId createQuestelPatentDocumentBibliographicDataPublicationReferenceDocumentId() {
        return new QuestelPatentDocument.BibliographicData.PublicationReference.DocumentId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "br", scope = QuestelPatentDocument.Description.P.class)
    public JAXBElement<Object> createQuestelPatentDocumentDescriptionPBr(Object value) {
        return new JAXBElement<Object>(_QuestelPatentDocumentDescriptionPBr_QNAME, Object.class, QuestelPatentDocument.Description.P.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "br", scope = QuestelPatentDocument.Abstract.P.class)
    public JAXBElement<Object> createQuestelPatentDocumentAbstractPBr(Object value) {
        return new JAXBElement<Object>(_QuestelPatentDocumentDescriptionPBr_QNAME, Object.class, QuestelPatentDocument.Abstract.P.class, value);
    }

}
